apiVersion: v1
kind: Service
metadata:
  name: 'atomaks-f452'
  labels:
    app: 'atomaks-f452'
spec:
  type: LoadBalancer
  ports:
    - port: 9002
      targetPort: 9002
      protocol: TCP
      name: http
  selector:
    app: 'atomaks-f452'
