apiVersion: v1
kind: Service
metadata:
    name: "atomaks-ef8e"
    labels:
        app: "atomaks-ef8e"
spec:
    type: LoadBalancer
    ports:
    - port: 9002
      targetPort: 9002
      protocol: TCP
      name: http
    selector:
        app: "atomaks-ef8e"